[build]
  # Frontend build command
  command = "cd frontend && npm ci && npm run build"
  
  # Output directory for the frontend
  publish = "frontend/out"
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Netlify environment flag
  NETLIFY = "true"

# Functions configuration
[functions]
  # Directory containing the functions
  directory = "netlify/functions"
  
  # Runtime for TypeScript functions
  node_bundler = "esbuild"
  
  # Include external node modules
  external_node_modules = ["pg-native"]

# Frontend routing for SPA
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# API headers for CORS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific settings
[context.production]
  command = "cd frontend && npm ci && NODE_ENV=production NETLIFY=true npm run build"

[context.deploy-preview]
  command = "cd frontend && npm ci && NODE_ENV=production NETLIFY=true npm run build"

[context.branch-deploy]
  command = "cd frontend && npm ci && NODE_ENV=production NETLIFY=true npm run build"